# Generated by Django 3.2.9 on 2022-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
